#!/usr/bin/env ruby
#
# Usage:
#
#   cat access.log | ASSET_PATH="/tmp" purge-files --purge
#
ASSETS_PATH = ENV["ASSET_PATH"] || "/var/cache/downloader/assets"
dry_run = !(ARGV[0] == "--purge")

raise "Nothing passed to STDIN" if STDIN.tty?

regex = /GET \/assets(\/\S+\/\S+) .+ 200/

STDIN.each do |line|
  line.chomp!

  if !(match = line.match(regex))
    next
  end

  fullpath = "#{ASSETS_PATH}#{match[1]}"

  if dry_run
    puts fullpath if File.exist?(fullpath)
  else
    File.delete(fullpath) rescue nil
  end
end
