#
# Deploy downloader to Production account via the skroutz-internal/aws-deploy-ecs-action action.
#
#   https://github.com/skroutz-internal/aws-deploy-ecs-action
#
name: Production deploy of Downloader to Amazon ECS on AWS Fargate

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  run-tests:
    uses: ./.github/workflows/ci.yml

  deploy-ecs:
    name: 'Production deployment of Downloader to Amazon ECS on AWS Fargate'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    needs: run-tests

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image, upload to ECR, and deploy to Amazon ECS
        uses: skroutz-internal/aws-deploy-ecs-action@v1
        with:
          ecr_repository: 'downloader'
          container_name: 'downloader'
          ecs_service: 'downloader-prod'
          ecs_cluster: 'downloader-prod'
          ecs_task_definition: 'aws_ecs/task_definition-production.json'
          wait_for_minutes: 7
          aws_gha_role_to_assume: ${{ secrets.AWS_GHA_ROLE_TO_ASSUME }}
          aws_gha_exec_role_to_assume: ${{ secrets.AWS_GHA_EXEC_ROLE_TO_ASSUME }}
